MyBundles\MyTestBundle\Entity\Author:
    type: entity
    table: authors
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        surname:
            type: string
            length: 255
    oneToMany:
        recipes:
            targetEntity: Recipe
            mappedBy: author